export type IconName =
  | 'Check'
  | 'ChevronDown'
  | 'File'
  | 'FileAudio'
  | 'FileCode'
  | 'FileImage'
  | 'FileJson'
  | 'FileText'
  | 'FileType'
  | 'FileVideo'
  | 'FolderClosed'
  | 'FolderOpen'
  | 'Github'
  | 'Menu'
  | 'Moon'
  | 'Sun';
